apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doctor-record-service-dev
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: doctor-record-service-dev
  project: default
  sources:
  - helm:
      valueFiles:
        - $values/charts/apps/meditrack/doctor-record-service/values/values-dev.yaml
    chart: common-application-charts
    repoURL: https://raw.githubusercontent.com/devops-homelab/homelab-helm-charts/gh-pages
    targetRevision: 1.0.4
  - repoURL: 'https://github.com/devops-homelab/homelab-gitops/'
    targetRevision: main
    ref: values    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  revisionHistoryLimit: 5

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: doctor-record-service-dev
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/devops-homelab/homelab-gitops
#     targetRevision: main
#     path: charts/apps/meditrack/doctor-record-service
#     helm:
#       valueFiles:
#         - values/values-dev.yaml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: doctor-record-service-dev
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#   revisionHistoryLimit: 3