apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mt-doctor-record-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/meditrack-org/mt-application-gitops
    targetRevision: main
    path: charts/application/meditrack/mt-doctor-record-service
    helm:
      valueFiles:
        - values/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mt-doctor-record-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3