apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mt-doctor-record-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devops-homelab/homelab-gitops
    targetRevision: main
    path: charts/apps/meditrack/mt-doctor-record-service
    helm:
      valueFiles:
        - values/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mt-doctor-record-service-dev
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - CreateNamespace=true
  revisionHistoryLimit: 3